package com.cake.bean;

public class address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phoneNumber
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phoneNumber
     *
     * @return the value of address.phoneNumber
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phoneNumber
     *
     * @param phonenumber the value for address.phoneNumber
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userID
     *
     * @return the value of address.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userID
     *
     * @param userid the value for address.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}