package com.cake.bean;

public class associateOrderAndProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associateOrderAndProduct.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associateOrderAndProduct.productId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associateOrderAndProduct.orderId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associateOrderAndProduct.id
     *
     * @return the value of associateOrderAndProduct.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associateOrderAndProduct.id
     *
     * @param id the value for associateOrderAndProduct.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associateOrderAndProduct.productId
     *
     * @return the value of associateOrderAndProduct.productId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associateOrderAndProduct.productId
     *
     * @param productid the value for associateOrderAndProduct.productId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associateOrderAndProduct.orderId
     *
     * @return the value of associateOrderAndProduct.orderId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associateOrderAndProduct.orderId
     *
     * @param orderid the value for associateOrderAndProduct.orderId
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}