package com.cake.bean;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.userID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.productID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.id
     *
     * @return the value of Cart.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.id
     *
     * @param id the value for Cart.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.userID
     *
     * @return the value of Cart.userID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.userID
     *
     * @param userid the value for Cart.userID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.productID
     *
     * @return the value of Cart.productID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.productID
     *
     * @param productid the value for Cart.productID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.number
     *
     * @return the value of Cart.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.number
     *
     * @param number the value for Cart.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}