package com.cake.bean;

public class flavour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavour.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavour.name
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavour.id
     *
     * @return the value of flavour.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavour.id
     *
     * @param id the value for flavour.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavour.name
     *
     * @return the value of flavour.name
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavour.name
     *
     * @param name the value for flavour.name
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}