package com.cake.bean;

public class order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.products
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer products;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    private Integer address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userID
     *
     * @return the value of order.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userID
     *
     * @param userid the value for order.userID
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.products
     *
     * @return the value of order.products
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getProducts() {
        return products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.products
     *
     * @param products the value for order.products
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setProducts(Integer products) {
        this.products = products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    public void setAddress(Integer address) {
        this.address = address;
    }
}