package com.cake.bean;

public class product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.size
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.relationID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer relationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.flavourID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer flavourid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.themeID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.photoPath
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private String photopath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.star
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.size
     *
     * @return the value of product.size
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.size
     *
     * @param size the value for product.size
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.relationID
     *
     * @return the value of product.relationID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getRelationid() {
        return relationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.relationID
     *
     * @param relationid the value for product.relationID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setRelationid(Integer relationid) {
        this.relationid = relationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.flavourID
     *
     * @return the value of product.flavourID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getFlavourid() {
        return flavourid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.flavourID
     *
     * @param flavourid the value for product.flavourID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setFlavourid(Integer flavourid) {
        this.flavourid = flavourid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.themeID
     *
     * @return the value of product.themeID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.themeID
     *
     * @param themeid the value for product.themeID
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setThemeid(Integer themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.photoPath
     *
     * @return the value of product.photoPath
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public String getPhotopath() {
        return photopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.photoPath
     *
     * @param photopath the value for product.photoPath
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setPhotopath(String photopath) {
        this.photopath = photopath == null ? null : photopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.star
     *
     * @return the value of product.star
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.star
     *
     * @param star the value for product.star
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.number
     *
     * @return the value of product.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.number
     *
     * @param number the value for product.number
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}