package com.cake.dao;

import com.cake.bean.address;
import com.cake.bean.addressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface addressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    long countByExample(addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    int deleteByExample(addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    int insert(address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    int insertSelective(address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    List<address> selectByExample(addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") address record, @Param("example") addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Wed Jul 24 10:55:29 CST 2019
     */
    int updateByExample(@Param("record") address record, @Param("example") addressExample example);
}