package com.cake.dao;

import com.cake.bean.flavour;
import com.cake.bean.flavourExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface flavourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    long countByExample(flavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int deleteByExample(flavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int insert(flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int insertSelective(flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    List<flavour> selectByExample(flavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    flavour selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") flavour record, @Param("example") flavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByExample(@Param("record") flavour record, @Param("example") flavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByPrimaryKeySelective(flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavour
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByPrimaryKey(flavour record);
}