package com.cake.dao;

import com.cake.bean.relationtype;
import com.cake.bean.relationtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface relationtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    long countByExample(relationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int deleteByExample(relationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int insert(relationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int insertSelective(relationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    List<relationtype> selectByExample(relationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    relationtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") relationtype record, @Param("example") relationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByExample(@Param("record") relationtype record, @Param("example") relationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByPrimaryKeySelective(relationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationtype
     *
     * @mbg.generated Wed Jul 24 09:58:14 CST 2019
     */
    int updateByPrimaryKey(relationtype record);
}